In [1]:
import requests 
import pandas as pd
import json
import numpy as np

In [2]:
def polygon_area(points):
    area = 0
    q = points[-1]
    for p in points:
        area += p[0] * q[1] - p[1] * q[0]
        q = p
    return area / 2

In [3]:
cores=["-77.018798,38.910730","-76.984152,38.904466","-76.991153,38.880580","-77.026214,38.895171",
      "-77.031821,38.905202","-77.042047,38.897675","-77.077305,38.913979","-77.059321,38.937563",
      "-77.036869,38.920003","-77.030272,38.933282","-77.023408,38.954521","-77.035392,38.977830",
      "-77.063297,38.966898","-77.092401,38.939452","-76.993028,38.938160","-76.971420,38.928633",
      "-76.937517,38.892334","-76.977764,38.860861","-77.021224,38.879790","-77.004226,38.832708",
      "-77.040762,38.908050","-77.052083,38.901120"]

In [4]:
profile=["driving/","walking/","cycling/"]
time=["10","30","60"]

In [5]:
part1="https://api.mapbox.com/isochrone/v1/mapbox/"
part2="?contours_minutes="
part3="&contours_colors=6706ce&polygons=true&access_token=pk.eyJ1IjoiY3VydmlubGVhdGhhbSIsImEiOiJGMXVtM2JzIn0.pUbDx_ITAx-VQzb0Z1Mkew"

In [6]:
areas10=[]
for i in range(22):
    core=cores[i]
    url=part1+"driving/"+core+part2+"10"+part3
    r=requests.get(url)
    a=json.loads(r.text)
    coor=a["features"][0]["geometry"]["coordinates"][0]
    polygon=np.array(coor)
    areas10.append(abs(polygon_area(coor)))

In [7]:
areas30=[]
for i in range(22):
    core=cores[i]
    url=part1+"driving/"+core+part2+"30"+part3
    r=requests.get(url)
    a=json.loads(r.text)
    coor=a["features"][0]["geometry"]["coordinates"][0]
    polygon=np.array(coor)
    areas30.append(abs(polygon_area(coor)))

In [8]:
areas60=[]
for i in range(22):
    core=cores[i]
    url=part1+"driving/"+core+part2+"60"+part3
    r=requests.get(url)
    a=json.loads(r.text)
    coor=a["features"][0]["geometry"]["coordinates"][0]
    polygon=np.array(coor)
    areas60.append(abs(polygon_area(coor)))

In [9]:
zip_code=['20001','20002','20003','20004','20005','20006','20007','20008','20009','20010','20011','20012',
         '20015','20016','20017','20018','20019','20020','20024','20032','20036','20037']

In [10]:
driving=pd.DataFrame(zip_code,columns={"Zip Code"})

In [22]:
driving

   Zip Code  Area of 10 mins  Area of 30 mins  Area of 60 mins
0     20001         0.001298         0.100731         0.795206
1     20002         0.001677         0.097053         0.746505
2     20003         0.002538         0.146583         0.914249
3     20004         0.002148         0.122541         0.886036
4     20005         0.001302         0.095574         0.814904
5     20006         0.001605         0.104250         0.861963
6     20007         0.001115         0.078914         0.791648
7     20008         0.002687         0.084780         0.806302
8     20009         0.001233         0.060864         0.703216
9     20010         0.001084         0.042408         0.634060
10    20011         0.002282         0.063188         0.696066
11    20012         0.002398         0.090074         0.799091
12    20015         0.002918         0.079460         0.763566
13    20016         0.002799         0.079344         0.774750
14    20017         0.002717         0.076420         0.687492
15    20018         0.003008         0.107316         0.768775
16    20019         0.002740         0.118127         0.798780
17    20020         0.000886         0.097072         0.767244
18    20024         0.002420         0.141702         0.923083
19    20032         0.002598         0.140899         0.862999
20    20036         0.001215         0.078797         0.767887
21    20037         0.002168         0.116169         0.908725

In [11]:
driving["Area of 10 mins"]=areas10
driving["Area of 30 mins"]=areas30
driving["Area of 60 mins"]=areas60

In [26]:
driving.to_csv("Driving Area 7 am.csv",index=False)

In [14]:
areas10b=[]
for i in range(22):
    core=cores[i]
    url=part1+"cycling/"+core+part2+"10"+part3
    r=requests.get(url)
    a=json.loads(r.text)
    coor=a["features"][0]["geometry"]["coordinates"][0]
    polygon=np.array(coor)
    areas10b.append(abs(polygon_area(coor)))

In [15]:
areas30b=[]
for i in range(22):
    core=cores[i]
    url=part1+"cycling/"+core+part2+"30"+part3
    r=requests.get(url)
    a=json.loads(r.text)
    coor=a["features"][0]["geometry"]["coordinates"][0]
    polygon=np.array(coor)
    areas30b.append(abs(polygon_area(coor)))

In [16]:
areas60b=[]
for i in range(22):
    core=cores[i]
    url=part1+"cycling/"+core+part2+"60"+part3
    r=requests.get(url)
    a=json.loads(r.text)
    coor=a["features"][0]["geometry"]["coordinates"][0]
    polygon=np.array(coor)
    areas60b.append(abs(polygon_area(coor)))

In [17]:
cycling=pd.DataFrame(zip_code,columns={"Zip Code"})

In [19]:
cycling["Area of 10 mins"]=areas10b
cycling["Area of 30 mins"]=areas30b
cycling["Area of 60 mins"]=areas60b

In [27]:
cycling.to_csv("Cycling Area 7 am.csv",index=False)

In [24]:
cycling

   Zip Code  Area of 10 mins  Area of 30 mins  Area of 60 mins
0     20001         0.001383         0.012722         0.047404
1     20002         0.001416         0.012399         0.048529
2     20003         0.001431         0.010347         0.045424
3     20004         0.001370         0.011214         0.047572
4     20005         0.001766         0.013283         0.050742
5     20006         0.001286         0.012212         0.047531
6     20007         0.000850         0.010504         0.042701
7     20008         0.001464         0.014334         0.048183
8     20009         0.001634         0.014183         0.049703
9     20010         0.001522         0.015090         0.047430
10    20011         0.001585         0.015238         0.046530
11    20012         0.001387         0.014885         0.044607
12    20015         0.001464         0.014879         0.048405
13    20016         0.001531         0.012527         0.047592
14    20017         0.001528         0.012463         0.042122
15    20018         0.001491         0.012352         0.042998
16    20019         0.001444         0.011473         0.035045
17    20020         0.000996         0.009400         0.032055
18    20024         0.001031         0.009700         0.045849
19    20032         0.000890         0.008281         0.032458
20    20036         0.001581         0.013291         0.049717
21    20037         0.001069         0.010764         0.043209